<<<<<<< HEAD
spring.application.name=springlab
=======
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=postgres
>>>>>>> 91a1414 (add REST controllers)
